#!/usr/bin/env node
'use strict';
// Writes deployable HTML. GitHub Pages serves docs/ directly; no client rendering is needed.
const fs = require('node:fs');
const path = require('node:path');
const source = path.join(__dirname, 'site');
const output = path.join(__dirname, '../docs');
const base = 'https://lemelson.github.io/xporter-extension/';
const store = 'https://chromewebstore.google.com/detail/jghmghialodmkmbcpfnhkgllkmjafmja';
const read = file => fs.readFileSync(path.join(source, file), 'utf8');
const escape = text => text.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
const copy = JSON.parse(read('translations.json'));
const updates = JSON.parse(read('content.json'));
for (const lang of ['en', 'ru']) Object.assign(copy[lang], updates[lang]);
// The secondary hero action now leads to setup rather than GitHub.
for (const lang of Object.keys(copy)) {
  if (lang !== 'en' && lang !== 'ru') delete copy[lang].hero_cta2;
}
const generated = new Map();
function emit(file, content) { generated.set(file, content); }
const template = read('home.html');
const usedKeys = new Set([...template.matchAll(/data-i18n(?:-html)?="([^"]+)"/g)].map(m => m[1]));
const browserCopy = Object.fromEntries(Object.entries(copy).map(([lang, values]) => [lang,
  Object.fromEntries(Object.entries(values).filter(([key]) => usedKeys.has(key) || key.startsWith('growth_')))
]));
emit('assets/site-copy.js', '// Generated by scripts/build-site.cjs.\nvar I18N = ' + JSON.stringify(browserCopy) + ';\n');
emit('assets/site.css', read('site.css') + '\n' + read('details.css'));
emit('assets/site.js', read('site.js'));
emit('assets/theme-init.js', `(function () {\n  try {\n    var saved = localStorage.getItem('xporter_theme');\n    var theme = saved === 'light' || saved === 'dark' ? saved : (matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light');\n    document.documentElement.setAttribute('data-theme', theme);\n  } catch (error) { document.documentElement.setAttribute('data-theme', 'dark'); }\n})();\n`);

for (const lang of ['en', 'ru']) {
  const prefix = lang === 'ru' ? '../' : './';
  const url = base + (lang === 'ru' ? 'ru/' : '');
  const c = copy[lang];
  const schema = {
    '@context': 'https://schema.org',
    '@graph': [
      { '@type': 'WebSite', '@id': base + '#website', url: base, name: 'XPorter', inLanguage: ['en', 'ru'] },
      { '@type': 'WebPage', '@id': url + '#webpage', url, name: c.page_title, description: c.page_description,
        inLanguage: lang, isPartOf: { '@id': base + '#website' }, about: { '@id': base + '#software' }, dateModified: '2026-09-10' },
      { '@type': 'SoftwareApplication', '@id': base + '#software', name: 'XPorter', url: base,
        description: copy.en.page_description, applicationCategory: 'BrowserApplication', operatingSystem: 'Desktop Chrome',
        softwareVersion: '2.0.0', downloadUrl: store,
        offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD', url: store },
        image: base + 'assets/social-preview.png', sameAs: [store, 'https://github.com/Lemelson/xporter-extension'],
        featureList: ['Posts and personal bookmarks', 'Followers, following and verified followers', 'CSV, XLSX and JSON', 'TXT for post-based exports', 'Local file generation', 'Date filters and resumable exports'] }
    ]
  };
  const head = `  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escape(c.page_title)}</title>
  <meta name="description" content="${escape(c.page_description)}" />
  <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1" />
  <meta name="referrer" content="strict-origin-when-cross-origin" />
  <meta name="google-site-verification" content="6Z2cj0kX7irYbmkR9JIBBW6sUhmadw8sFJx33zqTFNY" />
  <link rel="canonical" href="${url}" />
  <link rel="alternate" hreflang="en" href="${base}" />
  <link rel="alternate" hreflang="ru" href="${base}ru/" />
  <link rel="alternate" hreflang="x-default" href="${base}" />
  <link rel="alternate" type="text/plain" href="${prefix}llms-full.txt" title="XPorter product reference" />
  <link rel="sitemap" type="application/xml" href="${prefix}sitemap.xml" />
  <link rel="icon" type="image/png" href="${prefix}assets/icon128.png" />
  <meta property="og:type" content="website" />
  <meta property="og:site_name" content="XPorter" />
  <meta property="og:title" content="${escape(c.page_title)}" />
  <meta property="og:description" content="${escape(c.page_description)}" />
  <meta property="og:url" content="${url}" />
  <meta property="og:locale" content="${lang === 'ru' ? 'ru_RU' : 'en_US'}" />
  <meta property="og:locale:alternate" content="${lang === 'ru' ? 'en_US' : 'ru_RU'}" />
  <meta property="og:image" content="${base}assets/social-preview.png" />
  <meta property="og:image:width" content="1200" />
  <meta property="og:image:height" content="630" />
  <meta property="og:image:alt" content="XPorter — export X (Twitter) to CSV, XLSX, JSON and TXT" />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content="${escape(c.page_title)}" />
  <meta name="twitter:description" content="${escape(c.page_description)}" />
  <meta name="twitter:image" content="${base}assets/social-preview.png" />
  <meta name="twitter:image:alt" content="XPorter — export X (Twitter) to CSV, XLSX, JSON and TXT" />
  <script src="${prefix}assets/theme-init.js"></script>
  <link rel="stylesheet" href="${prefix}assets/site.css" />
  <script type="application/ld+json">${JSON.stringify(schema).replaceAll('<', '\\u003c')}</script>`;
  let html = read('home.html').replace('{{HEAD}}', head).replaceAll('{{ROOT}}', prefix)
    .replaceAll('{{LANG}}', lang).replaceAll('{{LANG_NAME}}', lang === 'ru' ? 'Русский' : 'English')
    .replaceAll('{{NAV_LABEL}}', lang === 'ru' ? 'Главная навигация' : 'Main navigation')
    .replaceAll('aria-label="Language"', 'aria-label="' + (lang === 'ru' ? 'Язык' : 'Language') + '"')
    .replaceAll('aria-label="Toggle theme"', 'aria-label="' + (lang === 'ru' ? 'Сменить тему' : 'Toggle theme') + '"');
  html = html.replace(/(<([a-z][a-z0-9]*)\b[^>]*\bdata-i18n(-html)?="([^"]+)"[^>]*>)([\s\S]*?)(<\/\2>)/g,
    (whole, start, tag, isHTML, key, old, end) => {
      if (!c[key]) throw new Error(`Missing ${lang} copy: ${key}`);
      return start + (isHTML ? c[key] : escape(c[key])) + end;
    });
  emit(lang === 'ru' ? 'ru/index.html' : 'index.html', '<!-- Generated by scripts/build-site.cjs; edit scripts/site/. -->\n' + html);
}

emit('sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
${['', 'ru/'].map(p => `  <url><loc>${base}${p}</loc><lastmod>2026-09-10</lastmod><xhtml:link rel="alternate" hreflang="en" href="${base}"/><xhtml:link rel="alternate" hreflang="ru" href="${base}ru/"/><xhtml:link rel="alternate" hreflang="x-default" href="${base}"/></url>`).join('\n')}
  <url><loc>${base}privacy-policy.html</loc><lastmod>2026-09-10</lastmod></url>
</urlset>
`);
emit('robots.txt', `# Project reference. On GitHub Pages crawlers read /robots.txt at the HOST root,
# not /xporter-extension/robots.txt. See deployment/SEO.md before installing.
User-agent: *
Allow: /

Sitemap: ${base}sitemap.xml
`);
emit('llms.txt', `# XPorter

> Free desktop Chrome extension for exporting accessible X (Twitter) posts, personal bookmarks and account lists. Files are generated locally. No API key or subscription.

Current Store version verified on 2026-09-10: 2.0.0, updated 2026-09-09.
X rate limits and data availability apply. Completeness is not guaranteed.
This is an independent product, not an official X product.

## Product documentation
- [English homepage](${base}): Capabilities, formats, setup, limits and FAQ.
- [Russian homepage](${base}ru/): Russian product information.
- [Full plain-text reference](${base}llms-full.txt): Product facts in English and Russian.
- [Privacy policy](${base}privacy-policy.html): Local data, permissions and uninstall diagnostics.
- [Chrome Web Store](${store}): Current published package and installation.
- [Source repository](https://github.com/Lemelson/xporter-extension): Source code; the main branch version may differ from the Store.

## Historical data
- [Growth snapshot](${base}assets/growth-forecast.json): Weekly users through July 16, 2026, and model scenarios. These are not current user counts.
`);
let reference = `# XPorter — product reference\n\nLast reviewed: 2026-09-10.\nOfficial website: ${base}\nChrome Web Store: ${store}\nStore version: 2.0.0 (updated 2026-09-09). The repository main branch may differ.\n\n`;
for (const lang of ['en', 'ru']) {
  const c = copy[lang];
  reference += `## ${lang === 'ru' ? 'Русский' : 'English'}\n\n${c.hero_lead}\n\n`;
  for (const [title, body] of [
    ['datasets_head', 'datasets_intro'], ['dataset_posts', 'dataset_posts_d'], ['dataset_bookmarks', 'dataset_bookmarks_d'],
    ['dataset_people', 'dataset_people_d'], ['format_csv', 'format_csv_d'], ['format_xlsx', 'format_xlsx_d'],
    ['format_json', 'format_json_d'], ['format_txt', 'format_txt_d'], ['how_head', 'how_sub'],
    ['s1_t', 's1_d'], ['s2_t', 's2_d'], ['s3_t', 's3_d'], ['s4_t', 's4_d'],
    ['controls_head', 'controls_d'], ['priv_t', 'priv_d'],
    ...['free', 'key', 'all', 'pause', 'photos', 'ai', 'browser', 'help'].map(k => [`faq_${k}_q`, `faq_${k}_a`]),
    ['growth_head', 'growth_sub']
  ]) reference += `### ${c[title]}\n\n${c[body]}\n\n`;
  reference += `${c.dataset_note}\n\n${c.priv_extra}\n\n`;
}
emit('llms-full.txt', reference.trimEnd() + '\n');
let stale = false;
for (const [file, value] of generated) {
  const dest = path.join(output, file);
  if (process.argv.includes('--check')) {
    if (!fs.existsSync(dest) || fs.readFileSync(dest, 'utf8') !== value) { console.error(`Stale generated site file: ${file}`); stale = true; }
  } else { fs.mkdirSync(path.dirname(dest), { recursive: true }); fs.writeFileSync(dest, value); }
}
if (stale) process.exit(1);
console.log(`${process.argv.includes('--check') ? 'Verified' : 'Built'} ${generated.size} site files.`);
